### ISSUE TITLE
How to disable login and registration?

### ISSUE THREAD

**Issue by dev-triboo** [creativetimofficial/soft-ui-dashboard-laravel#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

Hi I would like to know how to remove the login and let the dashboard available without registration.

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM.

In order to eliminate login and register functionality, you need to make the following changes in the routes/web.php file:

1.  Comment out the middleware `guest` and the routes inside it for login, register, forgot-password, etc. 

2. Additionally, you need to comment the Route::group(['middleware' => 'auth'], function () with closing parentheses and the lines with the routes for logout and login.

Thank you. Let us know if we can help you with anything else.
